services:
  nextjs:
    build: /nextjs
    ports:
      - '3000:3000'
    depends_on:
      - nestjs
      - mysql
    networks:
      - mynetwork

  nestjs:
    build: /nestjs
    ports:
      - '3001:3001'
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:
